spring.application.name=codesphere-auth-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/codesphere_auth_db
spring.datasource.username=postgres
spring.datasource.password=Naved@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*